### ISSUE TITLE
Error: java.io.FileNotFoundException: /storage/emulated/0/Download/helloworld.pdf: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by palikollar** [nativescript-community/ui-document-picker#14] opened 2021-10-28 20:12 UTC
Hey!

I would like to import file(s) from shared storage to my application's internal storage, however I got a permission denied error. I know this issue might not directly relate to this plugin, however I thought people here would know the solution and I might help others.

I have created a minimal reproduction of the issue, you can find it here: https://github.com/palikollar/ui-document-picker-demo

Given:
- emulator is Android 11 (API 30)
- I have uploaded a pdf file to this location on my android emulator /storage/emulated/0/Download/
- I click on "select a file" on the application
- I click allow when the plugin asks for permission

When:
- I select the uploaded pdf from /storage/emulated/0/Download/

Then:
- An error is thrown: **Error: java.io.FileNotFoundException: /storage/emulated/0/Download/helloworld.pdf: open failed: EACCES (Permission denied)**
- The file is not copied from shared storage to application internal storage

I think the issue might been introduced in android API 30, when they added scoped storage a more restrictive permission handling for android.

**Comment by JamesPoel** [comment] 2021-11-12 10:10
I also have this issue. Any updates?

**Comment by farfromrefug** [comment] 2021-11-12 10:33
duplicate of https://github.com/nativescript-community/ui-document-picker/issues/7

**Closed by farfromrefug** 2021-11-12 10:33 UTC

**Comment by palikollar** [comment] 2021-11-12 10:51
I have overcame this issue and you can use my solution: https://github.com/palikollar/ns-device-import-activity

I implemented my solution in Angular NS and it only works for android, I will probably keep using this package for ios.

I am using native Java to start the activity: https://github.com/palikollar/ns-device-import-activity/blob/master/App_Resources/Android/src/main/java/org/example/DeviceImportUtils.java

and I am waiting for the result here: https://github.com/palikollar/ns-device-import-activity/blob/master/src/app/activity.android.ts

You will still need to add some configuration and code, but please look through the commits for that.
